# Generated by Django 4.0.4 on 2022-05-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=60)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'ordering': ['-interest_rate'],
            },
        ),
    ]
